### ISSUE TITLE
How do you get past the "select opening provider" page on the launch page

### ISSUE THREAD

**Issue by SkyTheNerd** [JavaScythe/Bunker#28]
Hello, when I get to "select opening provider" none of the options work. What do I do to get past this?

**Comment by Cattn** [comment]
please tell me if it works or not

**Comment by SkyTheNerd** [comment]
It keeps saying TypeError: Cannot read properties of null (reading 'document')

**Comment by SkyTheNerd** [comment]
wait nvm it was because popups were blocked
