### ISSUE TITLE
so umm error and how should I install and also suggestion/help offer + really long title that no one will read in the eternity of time and space and so on and on and on...

### ISSUE THREAD

**Issue by animecat7** [JavaScythe/Bunker#31]
so when I open the index.html page it shows this almost blank page (I know im supposed to open the launcher.html) and Im suggesting adding a redirect in js like: `window.location.replace("/launcher.html");` I also want to request maybe a more detailed explanation of how to use, if there is enough info I coud make a tutrioul. I realize that you may have HW and things occupying your day, so I understand if this never happens, I would be more than happy to help if you need it.

**Comment by Cattn** [comment]
What exactly is hard to understand right now?

**Comment by JavaScythe** [comment]
there shouldn't be an index.html above version 5.
depending on if you used the new download or github releases you should have:
launcher.html
compiled.js
and with v7:
manifest.json
