### ISSUE TITLE
Zfs file wont pop up

### ISSUE THREAD

**Issue by tokyojoe1** [JavaScythe/Bunker#33]
When I download bunker (onto a chromebook), the zfs file wont pop up but the others will, what should I do about this?

**Comment by mathadventure1** [comment]
Which version are you downloading? the newest version?

**Comment by tokyojoe1** [comment]
> Which version are you downloading? the newest version?

Well i dont know but I am clicking code then download Zip so which version would that be ??

**Comment by tokyojoe1** [comment]
> Which version are you downloading? the newest version?

Nevermind, I just found out how to fix it because of you, thanks!!!

**Comment by Cattn** [comment]
no problem, just to make sure you realize, you download versions from the version tab, not from the actual code page, the code page is just raw uncompiled code, if you want to make your own version of bunker than you could fork that

**Comment by Cattn** [comment]
I was commenting on my alternate account before on accident lol
