### ISSUE TITLE
More options?

### ISSUE THREAD

**Issue by Viberiouss** [JavaScythe/Bunker#35]
It would be cool to have more options, since for the games there are only two providers.
Also maybe having themes, and a quick switch button to switch to a selected website, and maybe even a way to change the text at the home screen.

These are just suggestions I was thinking about, it would be a lifesaver if you added them!

**Comment by Viberiouss** [comment]
oh also website searching isn't working at all right now, any reasons why?

**Comment by Cattn** [comment]
What do you mean by website searching? If you mean the url frame loader, just to clarify it isn't a proxy you have to put a full unblocked link into it (https:// and everything) 

As for the options and stuff, thank you for the suggestions, we will be working on a major update over the summer so this is basically the only version that isn't a beta that will be around for a while as we completely redesign and make new things

**Comment by Viberiouss** [comment]
Okay nice, I thought it meant you could browse whatever, not that you put a proxy inside of it, thanks!
