### ISSUE TITLE
How To Install

### ISSUE THREAD

**Issue by animecat7** [JavaScythe/Bunker#36]
# A Guide For _Bunker_
### written animecat7
```
*This is UNOFFICIAL, and may break with future updates*
```
As _@JavaScythe_ probably knows, when I first tried to download I was very confused. I have learnt from my mistakes and have made a guide for anyone new to Bunker. 

I hope _@JavaScythe_  and _@Cattn_ decide to use this as the official guide, as the one by _@elisha1099_ is (no offense) overly complicated. <sup>You dont even need to use google drive, and if you do, your administration can view what you have on it</sup>

### Let The Guide(s) Begin!

1.) This is the small slide demo thingy I made to demonstrate on how you install:

[How To Install -the PDF](https://github.com/JavaScythe/Bunker/files/8796075/Untitled.Jam.1.pdf)

2.)This is the video that wouldn't load in the slides so I moved it out here:
<sub>im using the glitch cdn. pls dont hate me</sub>

[Video -bad quality,sry](https://cdn.glitch.global/d0afa14c-637b-4c3f-a808-0655ff6a3ca6/Screen%20recording%202022-05-29%2011.23.01%20PM%20(online-video-cutter.com)%20(1).mp4?v=1653895029585)

***
***
_I mean no disrespect to @elisha1099 when I said this, instead I would like to congratulate them on being the first person to write a guide on bunker._

**Comment by Cattn** [comment]
I'll add this soon i was on phone

**Comment by elisha1099** [comment]
Hey all, sorry I completely forgot I even made a guide on bunker and didn't realize you would actually see it. 😅 I made the guide more for my friends at school because they lock everything down (even github after they saw the guide I made) also as response to the discord question, my nitro ran out. My current discord is "elisha#4403".

**Comment by Cattn** [comment]
kk thanks for makin the og guide lol

**Comment by animecat7** [comment]
@elisha1099 your original guide was what inspired me to make this. At my school, we have Securly and GoGuardian. We also have WiFi blocks and the Chromebook itself is configured to block certain URLs. So I understand what you mean about the school locking down GitHub. My school actually suspended me for finding ways to get around GoGuardian for 2 weeks 😅.

**Comment by animecat7** [comment]
wait I closed this documentation. ima reopen it.

**Comment by Cattn** [comment]
check the readme this can be closed now, thanks for makin it
