### ISSUE TITLE
Assets Refusing to Connect/Load

### ISSUE THREAD

**Issue by HaxsMaster** [JavaScythe/Bunker#38]
Most sites that I attempt to use on Bunker refuse to connect. Directly attempting to access sites like google just gets the error message "Google refused to connect." Some proxies also refuse to connect. I am using a Chromebook in EGUSD, and I cannot access most proxies except Lunanom. If there is as solution please respond ASAP so I can actually use Bunker for its intended purpose. The games also refuse to load.

**Comment by JavaScythe** [comment]
bunker is NOT A PROXY
the url iframe thing is NOT A PROXY
some sites (like google.com) will refuse to connect in an iframe because of security protocols

as for the games check to see if both
- brhhst.vercel.app
- javascythe.github.io
are blocked

**Comment by HaxsMaster** [comment]
So if proxies are blocked on my chromebook, I cannot use said proxies, and I have to find another proxy correct?

**Comment by Cattn** [comment]
Yes you must use your own proxy, we have some proxies that we have made:
https://english.skystrike.ml although it is probably blocked, other than that best way of getting proxies is just joining some discord servers and tryna get links

**Comment by HaxsMaster** [comment]
Alright, thanks for the help.

**Comment by JavaScythe** [comment]
@HaxsMaster 
Did you check if the domains I specified in my previous comment were unblocked?

**Comment by HaxsMaster** [comment]
The Javascythe domain is blocked.
