### ISSUE TITLE
Compiling system

### ISSUE THREAD

**Issue by Paragramex** [JavaScythe/Bunker#43]
Uhhh so this isn't really an issue but how does the compiling work, like do you just run it like node compiler.js and watch it work or do you edit the file and then run. I'm asking because I want to use this with some of my own projects. If it's a trade secret than let me know and I won't bother you about this anymore.

**Comment by Cattn** [comment]
This project is discontinued, but as for compiling, you can try opening a CMD prompt in the folder of the source, and then do node index.js

but, as a fair warning the compiler was never meant for public use and tbh only @JavaScythe knows fully how it works, and can get it to work ever

**Comment by Cattn** [comment]
I'd suggest checking out https://github.com/Math-Study/bunker-v1/releases/ as it's a reboot of Bunker

We will be swapping to the style used here soon (A:B Cloak + maybe compiled)

**Comment by Paragramex** [comment]
ok, @JavaScythe can you explain the compiler?

**Comment by JavaScythe** [comment]
The compiler goes through every file in the entire project (including sub-directories) and adds a key in a json file with a value of the contents of the file (encoded in order to work with json)

**Comment by JavaScythe** [comment]
The following is the entire compiler code
I have added comments to explain it

```JS
const dree = require('dree');
const fs = require("fs");
var r = {"files": {}};
//ignore list for dree options
//ignoring files not used in bunker
const ignore = {
	"paths": [/git/, /node_modules/, /gitignored/, /zfs/],
	"files": [".gitignore", "/compiled.js", "/package.json", "/package-lock.json"],
}
const options = {
    depth: 5,
    exclude: ignore.paths,
    extensions: [ 'html', 'js', 'wasm', 'svg', "css" ]
};
function parseF(f){
	return f.replace(/'/g, "\'").replace(/"/g, "\"").replace(/`/g, "\`");
}
const fileCallback = function (file) {
       //convert file path to relative path
       //these values "workspace/E2EE-PARTY" were created specifically for my development enviroment
	const path = file.path.replace("/workspace/E2EE-PARTY", "");
	//check if specific file should be ignored
	if(ignore.files.indexOf(path)!=-1) return false;
	//add a key (path) with value (contents of file)
	r.files[path] = fs.readFileSync(__dirname+path, "utf-8");
};

let tree;
(async function(){
	tree = await dree.scan(__dirname, options, fileCallback); //scan directory and subdirectories
	fs.writeFileSync(__dirname+"/compiled.js", "window.__files="+JSON.stringify(r)); //write the compiled file to compiled.js
	console.log(`Compiled ${Object.keys(r.files).length} files to compiled.js`);
})();
```

**Comment by JavaScythe** [comment]
I would be more than happy to help you implement a similar system in one of your projects
(no credit necessary 😉)

**Comment by Paragramex** [comment]
thanks, your like the nicest developer I have met so far lmao

**Comment by Cattn** [comment]
The official repo has been edited with a more friendly version of the compiler to clear confusion going forward, I'm going to close this now
