### ISSUE TITLE
Where are the games stored?

### ISSUE THREAD

**Issue by Crazygird** [JavaScythe/Bunker#44]
I looked in the code and I can't find where the games are.

**Comment by Cattn** [comment]
they are hosted externally

**Comment by Crazygird** [comment]
bro hold up I found all of the games on javascythe.github.io *proceeds to get everything blocked

**Comment by JavaScythe** [comment]
https://github.com/JavaScythe/Bunker/blob/main/apps/sample-games/run.html
line 21 has the list
